name: Compile ESPHome BIN

on:
  push:
    paths:
      - '*.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install ESPHome
        run: pip install esphome

      - name: Compile Dashboard
        run: |
          for f in *.yaml; do
            esphome compile "$f"
          done

      - name: Advanced Copy for C3
        run: |
          mkdir -p final_output
          # 深度搜索所有的 bin 文件并集中复制过来
          find .esphome/build/ -name "*.bin" -exec cp {} ./final_output/ \; || true
          ls -la ./final_output

      - name: Upload BIN Artifact
        uses: actions/upload-artifact@v4
        with:
          name: esphome-bin-files
          path: final_output/*
