name: Compile ESPHome BIN

on:
  push:
    paths:
      - '*.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install ESPHome
        run: pip install esphome

      - name: Compile Dashboard
        run: |
          for f in *.yaml; do
            esphome compile "$f"
            # 兼容 ESP32-C3 等新芯片的固件路径查找
            mkdir -p ./output_bins
            find .esphome/build/ -name "firmware.bin" -exec cp {} ./output_bins/ \; || true
            find .esphome/build/ -name "firmware-factory.bin" -exec cp {} ./output_bins/ \; || true
          done

      - name: Upload BIN Artifact
        uses: actions/upload-artifact@v4
        with:
          name: esphome-bin-files
          path: "output_bins/*"
